### ISSUE TITLE
Can't compile: class GlooxClient has no member named setInactive

### ISSUE THREAD

**Issue by Scrumplex** [KaidanIM/Kaidan#234]
If I try to compile this I get this error:
```
/opt/Kaidan/src/ClientWorker.cpp: In member function ‘void ClientWorker::setApplicationState(Qt::ApplicationState)’:
/opt/Kaidan/src/ClientWorker.cpp:157:23: error: ‘class GlooxClient’ has no member named ‘setActive’; did you mean ‘setAuthed’?
   controller->client->setActive();
                       ^~~~~~~~~
                       setAuthed
/opt/Kaidan/src/ClientWorker.cpp:159:23: error: ‘class GlooxClient’ has no member named ‘setInactive’
   controller->client->setInactive();
                       ^~~~~~~~~~~
```
I tried it on KDE neon (xenial), Ubuntu 17.10 (artful) and Ubuntu 18.04 LTS (bionic). I always got this error.

**Comment by LNJ2** [comment]
You need the latest gloox version (1.0.19 or newer), unfortunately it wasn't updated in ubuntu or debian. But you can get our builds from here: https://github.com/KaidanIM/gloox-git/releases

**Comment by JBBgameich** [comment]
It's likely that our gloox debian sid gloox builds also work on Ubuntu 17.10, you can get them [here](https://github.com/KaidanIM/packages/tree/master/pool/main/g/gloox).

**Comment by Scrumplex** [comment]
The latest AppImage btw. does not work on KDE neon. It says that xcb plugin is not available. The prior version works

**Comment by JBBgameich** [comment]
The AppImage and the most recent relase as well are quite old. We will release a new version again in the future, but for now I recmmend using the master branch. I will try to fix the AppImage in the next release of course :)
